/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_App_DefaultOutputStream */

#ifndef _Included_jni_App_DefaultOutputStream
#define _Included_jni_App_DefaultOutputStream
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
